=== jharner/rspark-book/c2_data_sources/s3_xml/pointnemotemp.dtd
<!ELEMENT temperatures (variable,
    filename,
    filepath,
    subset,
    longitude,
    latitude,
    case*)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT filepath (#PCDATA)>
<!ELEMENT subset (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT case EMPTY>

<!ATTLIST case
    date ID #REQUIRED
    temperature CDATA #IMPLIED>

=== jharner/rspark-book/m2_data_sources/s3_xml/pointnemotemp.xml
<?xml version="1.0"?>
<!DOCTYPE temperatures SYSTEM "pointnemotemp.dtd">
<temperatures>
    <variable>Mean TS from clear sky composite (kelvin)</variable>
    <filename>ISCCPMonthly_avg.nc</filename>
    <filepath>/usr/local/fer_dsets/data/</filepath>
    <subset>93 points (TIME)</subset>
    <longitude>123.8W(-123.8)</longitude>
    <latitude>48.8S</latitude>
    <case date="16-JAN-1994" temperature="278.9"/>
    <case date="16-FEB-1994" temperature="280"/>
    <case date="16-MAR-1994" temperature="278.9"/>
    <case date="16-APR-1994" temperature="278.9"/>
    <case date="16-MAY-1994" temperature="277.8"/>
    <case date="16-JUN-1994" temperature="276.1"/>
    <case date="16-JUL-1994" temperature="276.1"/>
    <case date="16-AUG-1994" temperature="275.6"/>
    <case date="16-SEP-1994" temperature="275.6"/>
    <case date="16-OCT-1994" temperature="277.3"/>
    <case date="16-NOV-1994" temperature="276.7"/>
    <case date="16-DEC-1994" temperature="278.9"/>
    <case date="16-JAN-1995" temperature="281.6"/>
    <case date="16-FEB-1995" temperature="281.1"/>
    <case date="16-MAR-1995" temperature="280"/>
    <case date="16-APR-1995" temperature="278.9"/>
    <case date="16-MAY-1995" temperature="277.8"/>
    <case date="16-JUN-1995" temperature="276.7"/>
    <case date="16-JUL-1995" temperature="277.3"/>
    <case date="16-AUG-1995" temperature="276.1"/>
    <case date="16-SEP-1995" temperature="276.1"/>
    <case date="16-OCT-1995" temperature="276.7"/>
    <case date="16-NOV-1995" temperature="278.4"/>
    <case date="16-DEC-1995" temperature="277.8"/>
    <case date="16-JAN-1996" temperature="281.1"/>
    <case date="16-FEB-1996" temperature="283.2"/>
    <case date="16-MAR-1996" temperature="281.1"/>
    <case date="16-APR-1996" temperature="279.5"/>
    <case date="16-MAY-1996" temperature="278.4"/>
    <case date="16-JUN-1996" temperature="276.7"/>
    <case date="16-JUL-1996" temperature="276.1"/>
    <case date="16-AUG-1996" temperature="275.6"/>
    <case date="16-SEP-1996" temperature="275.6"/>
    <case date="16-OCT-1996" temperature="276.1"/>
    <case date="16-NOV-1996" temperature="277.3"/>
    <case date="16-DEC-1996" temperature="278.9"/>
    <case date="16-JAN-1997" temperature="280.5"/>
    <case date="16-FEB-1997" temperature="281.6"/>
    <case date="16-MAR-1997" temperature="280"/>
    <case date="16-APR-1997" temperature="278.9"/>
    <case date="16-MAY-1997" temperature="278.4"/>
    <case date="16-JUN-1997" temperature="276.7"/>
    <case date="16-JUL-1997" temperature="275.6"/>
    <case date="16-AUG-1997" temperature="275.6"/>
    <case date="16-SEP-1997" temperature="277.3"/>
    <case date="16-OCT-1997" temperature="276.7"/>
    <case date="16-NOV-1997" temperature="278.4"/>
    <case date="16-DEC-1997" temperature="279.5"/>
    <case date="16-JAN-1998" temperature="282.2"/>
    <case date="16-FEB-1998" temperature="281.6"/>
    <case date="16-MAR-1998" temperature="281.6"/>
    <case date="16-APR-1998" temperature="280"/>
    <case date="16-MAY-1998" temperature="278.9"/>
    <case date="16-JUN-1998" temperature="277.3"/>
    <case date="16-JUL-1998" temperature="276.7"/>
    <case date="16-AUG-1998" temperature="276.1"/>
    <case date="16-SEP-1998" temperature="276.1"/>
    <case date="16-OCT-1998" temperature="276.1"/>
    <case date="16-NOV-1998" temperature="277.8"/>
    <case date="16-DEC-1998" temperature="277.3"/>
    <case date="16-JAN-1999" temperature="278.4"/>
    <case date="16-FEB-1999" temperature="284.2"/>
    <case date="16-MAR-1999" temperature="279.5"/>
    <case date="16-APR-1999" temperature="277.3"/>
    <case date="16-MAY-1999" temperature="278.4"/>
    <case date="16-JUN-1999" temperature="275"/>
    <case date="16-JUL-1999" temperature="275.6"/>
    <case date="16-AUG-1999" temperature="274.4"/>
    <case date="16-SEP-1999" temperature="275.6"/>
    <case date="16-OCT-1999" temperature="276.7"/>
    <case date="16-NOV-1999" temperature="276.1"/>
    <case date="16-DEC-1999" temperature="278.4"/>
    <case date="16-JAN-2000" temperature="279.5"/>
    <case date="16-FEB-2000" temperature="279.5"/>
    <case date="16-MAR-2000" temperature="278.9"/>
    <case date="16-APR-2000" temperature="277.8"/>
    <case date="16-MAY-2000" temperature="277.8"/>
    <case date="16-JUN-2000" temperature="275.6"/>
    <case date="16-JUL-2000" temperature="275.6"/>
    <case date="16-AUG-2000" temperature="275"/>
    <case date="16-SEP-2000" temperature="274.4"/>
    <case date="16-OCT-2000" temperature="275.6"/>
    <case date="16-NOV-2000" temperature="277.3"/>
    <case date="16-DEC-2000" temperature="278.4"/>
    <case date="16-JAN-2001" temperature="281.1"/>
    <case date="16-FEB-2001" temperature="283.2"/>
    <case date="16-MAR-2001" temperature="281.1"/>
    <case date="16-APR-2001" temperature="279.5"/>
    <case date="16-MAY-2001" temperature="277.3"/>
    <case date="16-JUN-2001" temperature="276.7"/>
    <case date="16-JUL-2001" temperature="275.6"/>
    <case date="16-AUG-2001" temperature="274.4"/>
    <case date="16-SEP-2001" temperature="275"/>
</temperatures>
